services:
  - type: web
    name: bot-reglamento-ia
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: OPENAI_API_KEY
        fromSecret: OPENAI_API_KEY
